### ISSUE TITLE
Step missing assign workitem

### ISSUE THREAD

**Issue by bruun963** [microsoft/azuredevopslabs#301] opened 2019-08-12 19:49 UTC
"Set the Link type to Parent and search for “credit card” ". The work item first needs to be assigned, by default it's unassigned and therefore the workitem will not appear in the search results. The step of assigning the workitem is missing.

**Comment by EdKaim** [comment] 2019-08-12 21:17
The suggested items to link are pulled from your most recently edited items. if you make any change to the target work item (like assigning ownership), the feature should then show up at the top of the default suggestions.
However, this isn't necessary for the lab. If you run the search for "credit card" (explicitly clicking the search), the target feature should appear. I just confirmed it in a test project, so if that's not working for you, it's probably due to an issue during project creation.
We have had it happen where no work items for this particular project will show up during a query. This seems to have something to do with a silent failure somewhere during the automated demo project creation and was resolved by just re-creating the project.

**Closed** 2020-01-31 06:28 UTC
