### ISSUE TITLE
Sign in issue to Azure DevOps Generator 

### ISSUE THREAD

**Issue by kasunsjc** [microsoft/azuredevopslabs#316] opened 2019-09-03 06:38 UTC
When I try to sign in to Azure devops demo generator it doesn't redirect me to sign in page. it loads the same page. I tried few times with different browsers, but still the same issue existed

**Comment by aksh-h** [comment] 2019-09-03 07:11
Could you please let us know which Id you were using to login? You can write to AzureDevOpsDemoGenerator@service.microsoft.com

**Comment by kasunsjc** [comment] 2019-09-03 07:19
I'm using my hotmail ID. Thanks @aksh-h  I will write to above email !!

**Comment by aksh-h** [comment] 2019-09-03 09:03
Do you have organization in the logged in directory?

**Comment by kasunsjc** [comment] 2019-09-04 07:51
Yes I do

**Comment by aksh-h** [comment] 2019-09-05 06:23
Could you please retry?

**Comment by sriramdasbalaji** [comment] 2020-01-31 06:25
Hi,

Hope the issue is resolved. Closing this issue. 

Thanks

**Closed by sriramdasbalaji** 2020-01-31 06:25 UTC
